apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: backend-success-rate
  namespace: pern-app
  labels:
    app.kubernetes.io/component: analysis
    app.kubernetes.io/part-of: pern-stack
spec:
  args:
  - name: service-name
  - name: prometheus-server
    value: http://prometheus-server.monitoring.svc.cluster.local:80
  
  metrics:
  - name: success-rate
    interval: 30s
    count: 10
    successCondition: result[0] >= 0.95
    failureCondition: result[0] < 0.90
    provider:
      prometheus:
        address: "{{args.prometheus-server}}"
        query: |
          sum(rate(
            nginx_ingress_controller_requests_total{
              service="{{args.service-name}}",
              status!~"5.*"
            }[5m]
          )) / 
          sum(rate(
            nginx_ingress_controller_requests_total{
              service="{{args.service-name}}"
            }[5m]
          ))
  
  - name: p95-response-time
    interval: 30s
    count: 5
    successCondition: result[0] <= 500
    failureCondition: result[0] > 1000
    provider:
      prometheus:
        address: "{{args.prometheus-server}}"
        query: |
          histogram_quantile(0.95,
            sum(rate(nginx_ingress_controller_request_duration_seconds_bucket{
              service="{{args.service-name}}"
            }[5m])) by (le)
          ) * 1000

---
apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: backend-response-time
  namespace: pern-app
spec:
  args:
  - name: service-name
  - name: prometheus-server
    value: http://prometheus-server.monitoring.svc.cluster.local:80
  
  metrics:
  - name: avg-response-time
    interval: 30s
    count: 5
    successCondition: result[0] <= 300
    failureCondition: result[0] > 800
    provider:
      prometheus:
        address: "{{args.prometheus-server}}"
        query: |
          sum(rate(nginx_ingress_controller_request_duration_seconds_sum{
            service="{{args.service-name}}"
          }[5m])) / 
          sum(rate(nginx_ingress_controller_request_duration_seconds_count{
            service="{{args.service-name}}"
          }[5m])) * 1000
  
  - name: p99-response-time
    interval: 30s
    count: 3
    successCondition: result[0] <= 1000
    failureCondition: result[0] > 2000
    provider:
      prometheus:
        address: "{{args.prometheus-server}}"
        query: |
          histogram_quantile(0.99,
            sum(rate(nginx_ingress_controller_request_duration_seconds_bucket{
              service="{{args.service-name}}"
            }[5m])) by (le)
          ) * 1000

---
apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: backend-error-rate
  namespace: pern-app
spec:
  args:
  - name: service-name
  - name: prometheus-server
    value: http://prometheus-server.monitoring.svc.cluster.local:80
  
  metrics:
  - name: error-rate-4xx
    interval: 30s
    count: 5
    successCondition: result[0] <= 0.05
    failureCondition: result[0] > 0.10
    provider:
      prometheus:
        address: "{{args.prometheus-server}}"
        query: |
          sum(rate(
            nginx_ingress_controller_requests_total{
              service="{{args.service-name}}",
              status=~"4.*"
            }[5m]
          )) / 
          sum(rate(
            nginx_ingress_controller_requests_total{
              service="{{args.service-name}}"
            }[5m]
          ))
  
  - name: error-rate-5xx
    interval: 30s
    count: 5
    successCondition: result[0] <= 0.01
    failureCondition: result[0] > 0.05
    provider:
      prometheus:
        address: "{{args.prometheus-server}}"
        query: |
          sum(rate(
            nginx_ingress_controller_requests_total{
              service="{{args.service-name}}",
              status=~"5.*"
            }[5m]
          )) / 
          sum(rate(
            nginx_ingress_controller_requests_total{
              service="{{args.service-name}}"
            }[5m]
          ))

---
apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: backend-cpu-memory
  namespace: pern-app
spec:
  args:
  - name: service-name
  - name: prometheus-server
    value: http://prometheus-server.monitoring.svc.cluster.local:80
  
  metrics:
  - name: cpu-usage
    interval: 60s
    count: 3
    successCondition: result[0] <= 0.8
    failureCondition: result[0] > 0.9
    provider:
      prometheus:
        address: "{{args.prometheus-server}}"
        query: |
          avg(rate(container_cpu_usage_seconds_total{
            pod=~"backend-.*",
            container="backend"
          }[5m]))
  
  - name: memory-usage
    interval: 60s
    count: 3
    successCondition: result[0] <= 400000000
    failureCondition: result[0] > 500000000
    provider:
      prometheus:
        address: "{{args.prometheus-server}}"
        query: |
          avg(container_memory_usage_bytes{
            pod=~"backend-.*",
            container="backend"
          })
