apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: success-rate
  namespace: pern-app
spec:
  args:
  - name: service-name
  metrics:
  - name: success-rate
    interval: 10s
    successCondition: result[0] >= 0.95
    failureCondition: result[0] < 0.90
    provider:
      prometheus:
        address: http://prometheus-server.monitoring.svc.cluster.local:80
        query: |
          sum(irate(
            nginx_ingress_controller_requests{
              service="{{args.service-name}}",
              status!~"5.*"
            }[2m]
          )) / 
          sum(irate(
            nginx_ingress_controller_requests{
              service="{{args.service-name}}"
            }[2m]
          ))
  
  - name: avg-response-time
    interval: 10s
    successCondition: result[0] <= 500
    failureCondition: result[0] > 1000
    provider:
      prometheus:
        address: http://prometheus-server.monitoring.svc.cluster.local:80
        query: |
          sum(rate(nginx_ingress_controller_request_duration_seconds_sum{service="{{args.service-name}}"}[2m])) / 
          sum(rate(nginx_ingress_controller_request_duration_seconds_count{service="{{args.service-name}}"}[2m])) * 1000
