apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: pern-app-set
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  
  generators:
  # Git-based generator for environment-specific configurations
  - git:
      repoURL: https://github.com/mankinimbom/pern-gitops
      revision: HEAD
      directories:
      - path: apps/pern-app/overlays/*
        exclude: 'apps/pern-app/overlays/.*'
      template:
        metadata: {}
        spec:
          source:
            targetRevision: HEAD
          project: pern-app
  
  # Matrix generator combining environments with configuration
  - matrix:
      generators:
      - git:
          repoURL: https://github.com/mankinimbom/pern-gitops
          revision: HEAD
          files:
          - path: apps/pern-app/overlays/*/config.json
      - clusters:
          selector:
            matchLabels:
              environment: '{{.environment}}'
  
  # Merge generator for progressive delivery across environments
  - merge:
      mergeKeys: ['server']
      generators:
      - clusters:
          selector:
            matchLabels:
              argocd.argoproj.io/secret-type: cluster
      - git:
          repoURL: https://github.com/mankinimbom/pern-gitops
          revision: HEAD
          directories:
          - path: apps/pern-app/overlays/*

  template:
    metadata:
      name: 'pern-app-{{.path.basename}}'
      namespace: argocd
      labels:
        app.kubernetes.io/name: pern-app
        app.kubernetes.io/component: '{{.path.basename}}'
        app.kubernetes.io/part-of: pern-stack
        environment: '{{.path.basename}}'
      annotations:
        argocd.argoproj.io/manifest-generate-paths: '{{.path.path}}'
        notifications.argoproj.io/subscribe.on-sync-succeeded.slack: deployment-notifications
        notifications.argoproj.io/subscribe.on-health-degraded.slack: alert-notifications
      finalizers:
      - resources-finalizer.argocd.argoproj.io
      
    spec:
      project: pern-app
      
      source:
        repoURL: https://github.com/mankinimbom/pern-gitops
        targetRevision: HEAD
        path: '{{.path.path}}'
        
      destination:
        server: https://kubernetes.default.svc
        namespace: 'pern-app-{{.path.basename}}'
      
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
          allowEmpty: false
        
        syncOptions:
        - CreateNamespace=true
        - PrunePropagationPolicy=foreground
        - PruneLast=true
        - ApplyOutOfSyncOnly=true
        - RespectIgnoreDifferences=true
        - Replace=false
        
        retry:
          limit: 5
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 3m
        
        managedNamespaceMetadata:
          labels:
            environment: '{{.path.basename}}'
            managed-by: argocd
            app.kubernetes.io/part-of: pern-stack
          annotations:
            argocd.argoproj.io/tracking-id: 'pern-app-{{.path.basename}}'
      
      # Health checks and conditions
      ignoreDifferences:
      - group: argoproj.io
        kind: Rollout
        jsonPointers:
        - /spec/replicas
      - group: autoscaling
        kind: HorizontalPodAutoscaler
        jsonPointers:
        - /spec/targetRef/apiVersion
      
      # Information for better observability
      info:
      - name: Environment
        value: '{{.path.basename}}'
      - name: 'Git Revision'
        value: '{{.revision}}'
      - name: 'Repository'
        value: '{{.repoURL}}'
      
      # Progressive sync for production
      revisionHistoryLimit: 10
