apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - projects/appproject.yaml
  - projects/analysis-template.yaml
  - apps/pern-app-production.yaml
  - apps/pern-app-staging.yaml
