apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# Note: Namespaces are managed by overlays (pern-app-staging, pern-app-production)
# Each overlay will create its own namespace automatically
resources:
  - secrets.yaml
  # Excluding GHCR secrets from ArgoCD management to avoid template variable issues
  # - secrets/ghcr-secrets.yaml
  - rbac.yaml
  - backend.yaml
  - frontend.yaml
  - postgresql.yaml
  - redis.yaml
  - ingress.yaml
  - hpa.yaml
  - networkpolicies.yaml
  - poddisruptionbudgets.yaml
  - servicemonitor.yaml
images:
  - name: ghcr.io/mankinimbom/pern-backend
    newTag: "7963f5d"
  - name: ghcr.io/mankinimbom/pern-frontend
    newTag: "7963f5d"
