apiVersion: v1
kind: ServiceAccount
metadata:
  name: backend-sa
  labels:
    app.kubernetes.io/name: backend
    app.kubernetes.io/component: service-account
    app.kubernetes.io/part-of: pern-stack
  annotations:
    argocd.argoproj.io/sync-wave: "0"
automountServiceAccountToken: true
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: frontend-sa
  labels:
    app.kubernetes.io/name: frontend
    app.kubernetes.io/component: service-account
    app.kubernetes.io/part-of: pern-stack
  annotations:
    argocd.argoproj.io/sync-wave: "0"
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: approval-job-sa
  labels:
    app.kubernetes.io/name: approval-job
    app.kubernetes.io/component: service-account
    app.kubernetes.io/part-of: pern-stack
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
automountServiceAccountToken: true
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: backend-role
  annotations:
    argocd.argoproj.io/sync-wave: "0"
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list"]
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list"]
- apiGroups: ["monitoring.coreos.com"]
  resources: ["servicemonitors"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: approval-job-role
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
rules:
- apiGroups: ["argoproj.io"]
  resources: ["rollouts"]
  verbs: ["get", "list", "patch", "update"]
- apiGroups: [""]
  resources: ["pods", "pods/log"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: backend-rolebinding
  annotations:
    argocd.argoproj.io/sync-wave: "0"
subjects:
- kind: ServiceAccount
  name: backend-sa
roleRef:
  kind: Role
  name: backend-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: approval-job-rolebinding
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
subjects:
- kind: ServiceAccount
  name: approval-job-sa
roleRef:
  kind: Role
  name: approval-job-role
  apiGroup: rbac.authorization.k8s.io
