apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-secrets-sa
  namespace: pern-app
  annotations:
    vault.hashicorp.com/role: "pern-app"
    argocd.argoproj.io/sync-wave: "0"
---
# Simple Kubernetes secrets (replace External Secrets for now)
apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: pern-app
  labels:
    app.kubernetes.io/name: pern-app
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: pern-application
  annotations:
    argocd.argoproj.io/sync-wave: "0"
type: Opaque
stringData:
  database-url: "postgresql://postgres:yourpassword@postgresql-service:5432/pern_db"
  jwt-secret: "your-super-secret-jwt-key-change-in-production"
  redis-url: "redis://:your_redis_password@redis-service:6379"
---
apiVersion: v1
kind: Secret
metadata:
  name: postgresql-secret
  namespace: pern-app
  labels:
    app.kubernetes.io/name: pern-app
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: pern-application
  annotations:
    argocd.argoproj.io/sync-wave: "0"
type: Opaque
stringData:
  username: "postgres"
  password: "yourpassword"
  database: "pern_db"
---
apiVersion: v1
kind: Secret
metadata:
  name: redis-secret
  namespace: pern-app
  labels:
    app.kubernetes.io/name: pern-app
    app.kubernetes.io/component: cache
    app.kubernetes.io/part-of: pern-application
  annotations:
    argocd.argoproj.io/sync-wave: "0"
type: Opaque
stringData:
  password: "your_redis_password"