apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-secrets-sa
  annotations:
    vault.hashicorp.com/role: "pern-app"
---
# External Secrets Configuration - Replace hardcoded secrets with external secret management
apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  annotations:
    # TODO: Replace with external secret management (e.g., External Secrets Operator)
    external-secrets.io/backend-version: "1"
type: Opaque
stringData:
  # WARNING: These are example values - replace with actual external secret references
  database-url: "postgresql://postgres:REPLACE_WITH_ACTUAL_PASSWORD@postgresql-service:5432/pern_db"
  jwt-secret: "REPLACE_WITH_ACTUAL_JWT_SECRET_FROM_VAULT"
  redis-url: "redis://:REPLACE_WITH_ACTUAL_REDIS_PASSWORD@redis-service:6379"
---
apiVersion: v1
kind: Secret
metadata:
  name: postgresql-secret
  annotations:
    # TODO: Replace with external secret management
    external-secrets.io/postgresql-version: "1"
type: Opaque
stringData:
  # WARNING: Replace with actual external secret references
  username: "postgres"
  password: "REPLACE_WITH_ACTUAL_DB_PASSWORD"
  database: "pern_db"
---
apiVersion: v1
kind: Secret
metadata:
  name: redis-secret
  annotations:
    # TODO: Replace with external secret management
    external-secrets.io/redis-version: "1"
type: Opaque
stringData:
  # WARNING: Replace with actual external secret references
  password: "REPLACE_WITH_ACTUAL_REDIS_PASSWORD"