apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-secrets-sa
  annotations:
    vault.hashicorp.com/role: "pern-app"
---
# Simple Kubernetes secrets (replace External Secrets for now)
apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
type: Opaque
stringData:
  database-url: "postgresql://postgres:yourpassword@postgresql-service:5432/pern_db"
  jwt-secret: "your-super-secret-jwt-key-change-in-production"
  redis-url: "redis://:your_redis_password@redis-service:6379"
---
apiVersion: v1
kind: Secret
metadata:
  name: postgresql-secret
type: Opaque
stringData:
  username: "postgres"
  password: "yourpassword"
  database: "pern_db"
---
apiVersion: v1
kind: Secret
metadata:
  name: redis-secret
type: Opaque
stringData:
  password: "your_redis_password"