apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: backend-metrics
  namespace: pern-app
  labels:
    app: backend
    app.kubernetes.io/name: pern-app
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: pern-application
    release: prometheus
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  selector:
    matchLabels:
      app: backend
  endpoints:
  - port: http
    path: /metrics
    interval: 30s
    scrapeTimeout: 10s
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: postgresql-metrics
  namespace: pern-app
  labels:
    app: postgresql
    app.kubernetes.io/name: pern-app
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: pern-application
    release: prometheus
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  selector:
    matchLabels:
      app: postgresql
  endpoints:
  - port: postgres
    interval: 30s
    scrapeTimeout: 10s
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: redis-metrics
  namespace: pern-app
  labels:
    app: redis
    release: prometheus
spec:
  selector:
    matchLabels:
      app: redis
  endpoints:
  - port: redis
    interval: 30s
    scrapeTimeout: 10s