apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: longhorn-wffc-db
provisioner: driver.longhorn.io
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
parameters:
  numberOfReplicas: "3"
  staleReplicaTimeout: "30"
  fsType: "ext4"
  dataLocality: "best-effort"
  migratable: "true"
