apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: pern-app

resources:
  - ../../base

patches:
  - path: replica-patch.yaml
  - path: resource-patch.yaml
  - target:
      kind: Rollout
      name: backend
    path: rollout-backend-patch.yaml
  - target:
      kind: Rollout
      name: frontend
    path: rollout-frontend-patch.yaml

# Environment-specific configurations

# Production environment labels
commonLabels:
  environment: production
  tier: production
  app.kubernetes.io/component: full-stack
  app.kubernetes.io/managed-by: argocd
  app.kubernetes.io/part-of: pern-application

images:
  - name: ghcr.io/mankinimbom/pern-backend
    newTag: bd748c6ec45f8c15bc0c59f790b24c5385051111
  - name: ghcr.io/mankinimbom/pern-frontend
    newTag: bd748c6ec45f8c15bc0c59f790b24c5385051111
