apiVersion: v1
kind: Secret
metadata:
  name: ghcr-creds
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  labels:
    app.kubernetes.io/name: ghcr-secret
    app.kubernetes.io/component: image-pull-secret
    app.kubernetes.io/part-of: pern-stack
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: ${GITHUB_DOCKER_CONFIG_JSON}